### PR TITLE
feat(ts): add rules that required parserOptions

### LINKED ISSUE #112: Enable `@typescript-eslint/no-floating-promises` and `@typescript-eslint/no-misused-promises`
### Clear and concise description of the problem

It make sense to enable rules [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) and [no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises/). They can warn you not forget to `await` the async function. What why not enable them?

### Suggested solution

Enable `@typescript-eslint/no-floating-promises` and `@typescript-eslint/no-misused-promises`.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by ZanMinKian**
### Description

Closes #112

### CODE REVIEW

**Comment by antfu** [comment]
It's it possible to have a setting for users to toggle?

**Comment by ZanMinKian** [comment]
If we stick to `one line of config`, maybe this is the most convenient way to use, if we ignore the linting speed reduction. What about detecting `tsconfig.eslint.json` before `tsconfig.json`? Do you have any other suggestions or directions?

**Comment by antfu** [comment]
I think having this default is a reasonable choice. But I think users should have the ability to opt-out of this to improve the perf in case they want (same as they can always override rules).

I am looking for something like: https://eslint.org/docs/latest/user-guide/configuring/configuration-files#adding-shared-settings

```ts
{
  extends: '@antfu',
  settings: {
    useTSC: false
  }
}
```

But I am not sure if it's designed for a config preset to read.

**Comment by ZanMinKian** [comment]
`settings` field is designed for eslint plugins. See [here](https://eslint.org/docs/latest/developer-guide/working-with-plugins). Shareable eslint config like this repo maybe should not use `settings`. And we have no way to get the `settings` field content, except using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig).

We have to well document it that tell user should add `overrides: require('@antfu/eslint-config-ts').overrides.filter(o=>o. parser !== '@typescript-eslint/parser')` to improve lint speed.

**Comment by antfu** [comment]
Let's have it an see

**Pull request merged**
