### PR TITLE
feat: add nvim support for `isInEditor`

### PR DESCRIPTION
**Pull request by ryoppippi**
### Description
add nvim support for isInEditor

### CODE REVIEW

**Comment by thenbe** [comment]
There's really no harm in merging this either way, but wasn't `process.env.VIM` already detecting that you were in neovim? (i.e. `:lua =vim.env.VIM`)

Ref https://github.com/antfu/eslint-config/pull/365

**Comment by ryoppippi** [comment]
Oh, `:=vim.env.VIM` works for me!
and `:=vim.env.NVIM` is `nil.

But when I launch `:terminal`, and execute `echo 	$VIM`, no variable set,
However, executing `echo $NVIM` shows the Neovim's tmp dir.

So, idk we need this PR anymore, but if you know something, please tell me what is the difference
@thenbe

**Comment by ryoppippi** [comment]
I think `process.env.NVIM` is not appropriate for this situation.
This is good learning for me

**Comment by ryoppippi** [comment]
@thenbe 
you can see `:h $NVIM`

**Comment by thenbe** [comment]
The main purpose of `isInEditor` is to prevent some rules from running on save ([see here](https://github.com/antfu/eslint-config/issues/422#issuecomment-1999445670)) because they could get annoying. Instead `isInEditor` was introduced to constrain those rules to only run when eslint is invoked through the cli (either manually by user, or [pre-commit hook](https://github.com/antfu/eslint-config/issues/422#issuecomment-1998895883), etc).

I'm not familiar with the jobstart workflow myself, but if you're using jobstart and feel like those "aggressive" rules should not run during that sort of workflow then we should proceed with this PR and detect `process.env.NVIM`.

**Pull request merged**
