### PR TITLE
feat(basic): enable `no-implicit-coercion`

### PR DESCRIPTION
**Pull request by zanminkian**
### Description

1. Prevent some code like:
```js
const a = "3"
const b = 4 + +a // bad readability
const c = 4 + Number(a)  // good readability
```

2. Convert type in consistent way.

### Additional context

https://eslint.org/docs/latest/rules/no-implicit-coercion

### CODE REVIEW

**Comment by antfu** [comment]
I use + a lot, and I kinda like it. Definitely not `4 + +a`, but I think `const b = +a` is a valid use case

**Comment by zanminkian** [comment]
Let's say we have code below. The second line will pass successfully, while the third line will throw an TypeError.
We can't recognize it easily. So adding `+` before the variable to convert type maybe is not a good choice, IMHO.
```js
const x = '3'
const y = + +x // Valid
const z = ++x // Uncaught TypeError: Assignment to constant variable.
```

**Comment by antfu** [comment]
Emm, I am not convinced. I personally would never write `+ +x`. If absolutely needed, I would write `(+a) + (+b)`. While on the other hand, I could avoid using `++x` or `x++` in favor of `x += 1`.

My philosophy is that the code should be as concise as possible, that why I omit the semicolons and unnecessary brackets. To me `+a` reads perfectly, but `Number(a)` is a bit too verbose.

**Comment by antfu** [comment]
Thanks for bringing this up. I don't think we are going with this any sooner, so let's close it to make it clear.

**Pull request closed without merging**
