### PR TITLE
feat!: Vue version auto detection

### PR DESCRIPTION
**Pull request by cloydlau**
### Description

After debugging, I found that https://github.com/antfu/eslint-config/issues/443 is not a bug but rather missing documentation. I will submit two PRs (for two different solutions) to address this issue: one for automatic detection of the Vue version (this one), and another for documentation improvement: https://github.com/antfu/eslint-config/pull/445. Additionally, I've changed `vue.vueVersion` to `vue.version` for a more streamlined configuration. (It's a breaking change). You can choose the solution you think is appropriate to merge, thanks.

### Linked Issues

https://github.com/antfu/eslint-config/issues/443

### CODE REVIEW

**Comment by antfu** [comment]
Thank you but no. We did that on purpose, as Vue 2 has already reached EOL, and there is no reason for me to actively support it anymore. Auto-detection would be the overhead that I don't think is worth taking either.

**Comment by cloydlau** [comment]
OK. But the documentation improvement is not acceptable either? The configuration `vue.vueVersion` does exists, but the user has no way to know that.

**Comment by antfu** [comment]
That's why it's important to have each PR atomic - so they can be discussed and merged separately. I can't take this PR as-is.

**Comment by cloydlau** [comment]
I see. The another PR: https://github.com/antfu/eslint-config/pull/445 contains three changes:
1. Feature description
2. Explain how to configure Vue version
3. Rename `vue.vueVersion` to `vue.version`
I understand that 1 should be removed. 2 is acceptable. So would you accept 3? I can submit a new PR.

**Comment by antfu** [comment]
I don't think 3 is necessary; breaking changes should always be avoided if possible. And I named it `vueVersion` to be specific that it's about Vue (not `vue-router`, `volar` or the version of package itself).

**Comment by cloydlau** [comment]
OK. I've submitted a new PR for 2.

**Pull request closed without merging**
